### ISSUE TITLE
Run issue on Ubuntu 16.04 (Xenial)

### ISSUE THREAD

**Issue by yangxuelei** [teto/pymptcpanalyzer#16]
I tried to run mptcpdump on Ubuntu 16.04, after installing it with "pip3 install mptcpanalzyer --user". The installation of mptcpanalzyer and its dependencies was successful. But the program does not start:

Traceback (most recent call last):
  File "/home/long/.local/bin/mptcpanalyzer", line 7, in <module>
    from mptcpanalyzer.cli import main
  File "/home/long/.local/lib/python3.5/site-packages/mptcpanalyzer/__init__.py", line 3, in <module>
    from enum import Enum, IntEnum, Flag, auto
ImportError: cannot import name 'Flag'

How to reproduce: just start "mptcpanalyzer".

**Comment by dreibh** [comment]
I can confirm the issue on an Ubuntu 16.04 x86_64 system:

nornetpp@dingo:~$ sudo apt install python3-pip
[sudo] password for nornetpp: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libexpat1-dev libpython3-dev libpython3.5-dev python-pip-whl python3-dev python3-setuptools python3-wheel python3.5-dev
Suggested packages:
  python-setuptools-doc
The following NEW packages will be installed:
  libexpat1-dev libpython3-dev libpython3.5-dev python-pip-whl python3-dev python3-pip python3-setuptools python3-wheel python3.5-dev
0 upgraded, 9 newly installed, 0 to remove and 1 not upgraded.
Need to get 39,2 MB of archives.
After this operation, 57,3 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://no.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libexpat1-dev amd64 2.1.0-7ubuntu0.16.04.3 [115 kB]
Get:2 http://no.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libpython3.5-dev amd64 3.5.2-2ubuntu0~16.04.5 [37,3 MB]
Get:3 http://no.archive.ubuntu.com/ubuntu xenial/main amd64 libpython3-dev amd64 3.5.1-3 [6 926 B]
Get:4 http://no.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 python-pip-whl all 8.1.1-2ubuntu0.4 [1 110 kB]
Get:5 http://no.archive.ubuntu.com/ubuntu xenial-updates/main amd64 python3.5-dev amd64 3.5.2-2ubuntu0~16.04.5 [413 kB]
Get:6 http://no.archive.ubuntu.com/ubuntu xenial/main amd64 python3-dev amd64 3.5.1-3 [1 186 B]
Get:7 http://no.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 python3-pip all 8.1.1-2ubuntu0.4 [109 kB]
Get:8 http://no.archive.ubuntu.com/ubuntu xenial/main amd64 python3-setuptools all 20.7.0-1 [88,0 kB]
Get:9 http://no.archive.ubuntu.com/ubuntu xenial/universe amd64 python3-wheel all 0.29.0-1 [48,1 kB]
Fetched 39,2 MB in 3s (9 930 kB/s)       
Selecting previously unselected package libexpat1-dev:amd64.
(Reading database ... 383599 files and directories currently installed.)
Preparing to unpack .../libexpat1-dev_2.1.0-7ubuntu0.16.04.3_amd64.deb ...
Unpacking libexpat1-dev:amd64 (2.1.0-7ubuntu0.16.04.3) ...
Selecting previously unselected package libpython3.5-dev:amd64.
Preparing to unpack .../libpython3.5-dev_3.5.2-2ubuntu0~16.04.5_amd64.deb ...
Unpacking libpython3.5-dev:amd64 (3.5.2-2ubuntu0~16.04.5) ...
Selecting previously unselected package libpython3-dev:amd64.
Preparing to unpack .../libpython3-dev_3.5.1-3_amd64.deb ...
Unpacking libpython3-dev:amd64 (3.5.1-3) ...
Selecting previously unselected package python-pip-whl.
Preparing to unpack .../python-pip-whl_8.1.1-2ubuntu0.4_all.deb ...
Unpacking python-pip-whl (8.1.1-2ubuntu0.4) ...
Selecting previously unselected package python3.5-dev.
Preparing to unpack .../python3.5-dev_3.5.2-2ubuntu0~16.04.5_amd64.deb ...
Unpacking python3.5-dev (3.5.2-2ubuntu0~16.04.5) ...
Selecting previously unselected package python3-dev.
Preparing to unpack .../python3-dev_3.5.1-3_amd64.deb ...
Unpacking python3-dev (3.5.1-3) ...
Selecting previously unselected package python3-pip.
Preparing to unpack .../python3-pip_8.1.1-2ubuntu0.4_all.deb ...
Unpacking python3-pip (8.1.1-2ubuntu0.4) ...
Selecting previously unselected package python3-setuptools.
Preparing to unpack .../python3-setuptools_20.7.0-1_all.deb ...
Unpacking python3-setuptools (20.7.0-1) ...
Selecting previously unselected package python3-wheel.
Preparing to unpack .../python3-wheel_0.29.0-1_all.deb ...
Unpacking python3-wheel (0.29.0-1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up libexpat1-dev:amd64 (2.1.0-7ubuntu0.16.04.3) ...
Setting up libpython3.5-dev:amd64 (3.5.2-2ubuntu0~16.04.5) ...
Setting up libpython3-dev:amd64 (3.5.1-3) ...
Setting up python-pip-whl (8.1.1-2ubuntu0.4) ...
Setting up python3.5-dev (3.5.2-2ubuntu0~16.04.5) ...
Setting up python3-dev (3.5.1-3) ...
Setting up python3-pip (8.1.1-2ubuntu0.4) ...
Setting up python3-setuptools (20.7.0-1) ...
Setting up python3-wheel (0.29.0-1) ...
nornetpp@dingo:~$ pip3 install mptcpanalyzer --user
Collecting mptcpanalyzer
  Downloading https://files.pythonhosted.org/packages/45/a0/0e0ce4722c69ac6831ad7b699a591e99f4f8b7679c3cf9817c27aa67c96f/mptcpanalyzer-0.3-py3-none-any.whl (85kB)
    100% |████████████████████████████████| 92kB 3.1MB/s 
Collecting matplotlib (from mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/89/61/465fb3bfba684b0f53b5c4829c3c89e86e6fe9fdcdfda93e38f1788090f0/matplotlib-3.0.3-cp35-cp35m-manylinux1_x86_64.whl (13.0MB)
    100% |████████████████████████████████| 13.0MB 90kB/s 
Collecting cmd2>=0.9 (from mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/9d/7c/fc946c24dfe4b12ffdcd099216471c413bbcf48f94f86b91b4ea44ccbaa6/cmd2-0.9.12-py3-none-any.whl (92kB)
    100% |████████████████████████████████| 102kB 6.4MB/s 
Collecting pandas>=0.23 (from mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/74/24/0cdbf8907e1e3bc5a8da03345c23cbed7044330bb8f73bb12e711a640a00/pandas-0.24.2-cp35-cp35m-manylinux1_x86_64.whl (10.0MB)
    100% |████████████████████████████████| 10.0MB 108kB/s 
Collecting stevedore (from mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/c6/dc/6ee92bccfe3c0448786b30b693e6060d62ec8c4a3ec9a287bac1c1a8d8c9/stevedore-1.30.1-py2.py3-none-any.whl (42kB)
    100% |████████████████████████████████| 51kB 7.7MB/s 
Collecting numpy>=1.10.0 (from matplotlib->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/f6/f3/cc6c6745347c1e997cc3e58390584a250b8e22b6dfc45414a7d69a3df016/numpy-1.16.3-cp35-cp35m-manylinux1_x86_64.whl (17.2MB)
    100% |████████████████████████████████| 17.2MB 61kB/s 
Collecting cycler>=0.10 (from matplotlib->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting python-dateutil>=2.1 (from matplotlib->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)
    100% |████████████████████████████████| 235kB 2.8MB/s 
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/dd/d9/3ec19e966301a6e25769976999bd7bbe552016f0d32b577dc9d63d2e0c49/pyparsing-2.4.0-py2.py3-none-any.whl (62kB)
    100% |████████████████████████████████| 71kB 7.5MB/s 
Collecting kiwisolver>=1.0.1 (from matplotlib->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/7e/31/d6fedd4fb2c94755cd101191e581af30e1650ccce7a35bddb7930fed6574/kiwisolver-1.0.1-cp35-cp35m-manylinux1_x86_64.whl (949kB)
    100% |████████████████████████████████| 952kB 1.3MB/s 
Collecting wcwidth>=0.1.7 (from cmd2>=0.9->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting colorama (from cmd2>=0.9->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting pyperclip>=1.5.27 (from cmd2>=0.9->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/2d/0f/4eda562dffd085945d57c2d9a5da745cfb5228c02bc90f2c74bbac746243/pyperclip-1.7.0.tar.gz
Collecting attrs>=16.3.0 (from cmd2>=0.9->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Collecting pytz>=2011k (from pandas>=0.23->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/3d/73/fe30c2daaaa0713420d0382b16fbb761409f532c56bdcc514bf7b6262bb6/pytz-2019.1-py2.py3-none-any.whl (510kB)
    100% |████████████████████████████████| 512kB 2.2MB/s 
Collecting six>=1.10.0 (from stevedore->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting pbr!=2.1.0,>=2.0.0 (from stevedore->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/14/09/12fe9a14237a6b7e0ba3a8d6fcf254bf4b10ec56a0185f73d651145e9222/pbr-5.1.3-py2.py3-none-any.whl (107kB)
    100% |████████████████████████████████| 112kB 6.0MB/s 
Collecting setuptools (from kiwisolver>=1.0.1->matplotlib->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl (575kB)
    100% |████████████████████████████████| 583kB 2.0MB/s 
Building wheels for collected packages: pyperclip
  Running setup.py bdist_wheel for pyperclip ... done
  Stored in directory: /home/nornetpp/.cache/pip/wheels/92/f0/ac/2ba2972034e98971c3654ece337ac61e546bdeb34ca960dc8c
Successfully built pyperclip
Installing collected packages: numpy, six, cycler, python-dateutil, pyparsing, setuptools, kiwisolver, matplotlib, wcwidth, colorama, pyperclip, attrs, cmd2, pytz, pandas, pbr, stevedore, mptcpanalyzer
Successfully installed attrs cmd2 colorama cycler kiwisolver matplotlib mptcpanalyzer numpy pandas pbr pyparsing pyperclip python-dateutil pytz setuptools-20.7.0 six-1.10.0 stevedore wcwidth
You are using pip version 8.1.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
nornetpp@dingo:~$ mptcp^C
nornetpp@dingo:~$ ~/.local/bin/mptcpanalyzer 
Traceback (most recent call last):
  File "/home/nornetpp/.local/bin/mptcpanalyzer", line 7, in <module>
    from mptcpanalyzer.cli import main
  File "/home/nornetpp/.local/lib/python3.5/site-packages/mptcpanalyzer/__init__.py", line 3, in <module>
    from enum import Enum, IntEnum, Flag, auto
ImportError: cannot import name 'Flag'

**Comment by teto** [comment]
Flag was introduced in python3.6 (https://docs.python.org/3/library/enum.html#enum.Flag) so it won't work with 3.5, I will bump the setup.py to match this. Thanks for the report.

**Comment by teto** [comment]
The fix was already in master. I just need to create a new release so that the fix propagates.
